# Generated by Django 4.2 on 2023-04-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_category_liske_category_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='liske',
            new_name='likes',
        ),
    ]
